config/routes.rb
Rails.application.routes.draw do
  resources :companies
  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :cnpj, :ie, :im, :phone, :zipcode, :address, :number, :neighborhood, :city, :state)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/_form.html.erb
<%= form_for @company, :html => { :class => "form-horizontal company" } do |f| %>

  <% if @company.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @company.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :cnpj, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :cnpj, :class => 'form-control' %>
    </div>
    <%=f.error_span(:cnpj) %>
  </div>
  <div class="form-group">
    <%= f.label :ie, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :ie, :class => 'form-control' %>
    </div>
    <%=f.error_span(:ie) %>
  </div>
  <div class="form-group">
    <%= f.label :im, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :im, :class => 'form-control' %>
    </div>
    <%=f.error_span(:im) %>
  </div>
  <div class="form-group">
    <%= f.label :phone, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:phone) %>
  </div>
  <div class="form-group">
    <%= f.label :zipcode, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :zipcode, :class => 'form-control' %>
    </div>
    <%=f.error_span(:zipcode) %>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <%=f.error_span(:address) %>
  </div>
  <div class="form-group">
    <%= f.label :number, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :number, :class => 'form-control' %>
    </div>
    <%=f.error_span(:number) %>
  </div>
  <div class="form-group">
    <%= f.label :neighborhood, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :neighborhood, :class => 'form-control' %>
    </div>
    <%=f.error_span(:neighborhood) %>
  </div>
  <div class="form-group">
    <%= f.label :city, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :city, :class => 'form-control' %>
    </div>
    <%=f.error_span(:city) %>
  </div>
  <div class="form-group">
    <%= f.label :state, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :state, :class => 'form-control' %>
    </div>
    <%=f.error_span(:state) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                companies_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/companies/edit.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/companies/index.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:cnpj) %></th>
      <th><%= model_class.human_attribute_name(:ie) %></th>
      <th><%= model_class.human_attribute_name(:im) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:zipcode) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:number) %></th>
      <th><%= model_class.human_attribute_name(:neighborhood) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to company.id, company_path(company) %></td>
        <td><%= company.name %></td>
        <td><%= company.cnpj %></td>
        <td><%= company.ie %></td>
        <td><%= company.im %></td>
        <td><%= company.phone %></td>
        <td><%= company.zipcode %></td>
        <td><%= company.address %></td>
        <td><%= company.number %></td>
        <td><%= company.neighborhood %></td>
        <td><%= company.city %></td>
        <td><%= company.state %></td>
        <td><%=l company.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_company_path(company), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      company_path(company),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_company_path,
            :class => 'btn btn-primary' %>

app/views/companies/new.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/companies/show.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @company.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cnpj) %>:</strong></dt>
  <dd><%= @company.cnpj %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ie) %>:</strong></dt>
  <dd><%= @company.ie %></dd>
  <dt><strong><%= model_class.human_attribute_name(:im) %>:</strong></dt>
  <dd><%= @company.im %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @company.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:zipcode) %>:</strong></dt>
  <dd><%= @company.zipcode %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @company.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:number) %>:</strong></dt>
  <dd><%= @company.number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:neighborhood) %>:</strong></dt>
  <dd><%= @company.neighborhood %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @company.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @company.state %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              companies_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_company_path(@company), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              company_path(@company),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script type="text/javascript" src="js/jquery.js"></script>
    <script type="text/javascript" src="js/jquery.maskedinput.js"></script>
    
    <title><%= content_for?(:title) ? yield(:title) : "Prothesis" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag :application %>
    <%= csrf_meta_tag %>   

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <!-- favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' -->

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <!--favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'-->

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <!--favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'-->

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <!-- favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' -->

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <!--  favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' -->

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <a class="navbar-brand" href="#">Prothesis</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Menu</h3>
            <ul class="nav nav-list">
              <li class="nav-header"></li>
              <li><%= link_to "Companies", companies_path  %></li>              
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/welcome/index.html.erb
<h1>Prothesis</h1>
<p>Welcome!</p>